SELECT COUNT(*) AS "cnt"
FROM KB_DOCUMENTS kd
WHERE kd.ENABLED = 1
  AND kd.CATEGORY_ID IN (
    SELECT CATEGORY_ID FROM KB_CATEGORIES
    START WITH CATEGORY_ID = :cid
    CONNECT BY PRIOR CATEGORY_ID = PARENT_ID
  )
