UPDATE KB_DOCUMENTS
SET STATUS='indexing', VECTORS=0, CHUNKS=0,
    INDEX_STATUS='queued', INDEX_PROGRESS=0,
    INDEX_STAGE='queued', INDEX_MESSAGE='재인덱싱 대기 중',
    INDEX_UPDATED_AT=TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    UPDATED_AT=SYSTIMESTAMP
WHERE DOC_ID=:did
