SELECT VERSION_ID AS "id", PRODUCT_ID AS "productId", VERSION_TAG AS "tag",
       VERSION_NUM AS "num", TO_CHAR(EOL_DATE,'YYYY-MM-DD') AS "eolDate", ACTIVE_FLAG AS "activeFlag"
FROM KB_PRODUCT_VERSIONS
WHERE PRODUCT_ID = :pid AND ACTIVE_FLAG = 1
ORDER BY VERSION_NUM
