UPDATE KB_DOCUMENTS
SET INDEX_STATUS   = :status,
    INDEX_PROGRESS = :prog,
    INDEX_STAGE    = :stage,
    INDEX_MESSAGE  = :msg,
    INDEX_UPDATED_AT = TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    UPDATED_AT     = SYSTIMESTAMP
WHERE DOC_ID = :did
