UPDATE KB_DOCUMENTS d SET
  d.VERSION_MIN_NUM = (
    SELECT MIN(pv.VERSION_NUM) FROM KB_DOCUMENT_VERSIONS dv
    JOIN KB_PRODUCT_VERSIONS pv ON pv.VERSION_TAG = dv.VERSION AND pv.PRODUCT_ID = :pid
    WHERE dv.DOC_ID = :did
  ),
  d.VERSION_MAX_NUM = (
    SELECT MAX(pv.VERSION_NUM) FROM KB_DOCUMENT_VERSIONS dv
    JOIN KB_PRODUCT_VERSIONS pv ON pv.VERSION_TAG = dv.VERSION AND pv.PRODUCT_ID = :pid
    WHERE dv.DOC_ID = :did
  )
WHERE d.DOC_ID = :did
