SELECT ep.EVENT_ID AS "eventId", ep.USER_ID AS "userId", u.DISPLAY_NAME AS "name", ep.ROLE AS "role"
FROM EVENT_PARTICIPANTS ep
JOIN USERS u ON u.USER_ID = ep.USER_ID
WHERE ep.EVENT_ID IN (/*PLACEHOLDER*/)
ORDER BY ep.EVENT_ID, ep.ROLE, u.DISPLAY_NAME
