/**
 * 파일: backend/src/modules/weekly-report/schema/weeklyReportSchema.js
 * 역할: 주간업무보고 테이블 DDL.
 *       WEEKLY_REPORTS(팀×주차 단위 보고서), WEEKLY_REPORT_ITEMS(엔지니어별 항목).
 *       TEAM_ID는 DEPARTMENTS.DEPT_ID를 팀으로 사용.
 *
 * 연관 파일:
 *   - repository/weeklyReportRepository.js
 *   - backend/src/server.js : 스키마 초기화
 */

import { isAlreadyExists } from '../../../infra/oracle/errorCodes.js';

const DDL = [
  `
    CREATE TABLE WEEKLY_REPORTS (
      REPORT_ID   NUMBER            GENERATED BY DEFAULT ON NULL AS IDENTITY,
      TEAM_ID     NUMBER,
      WEEK_START  DATE              NOT NULL,
      WEEK_END    DATE              NOT NULL,
      STATUS      VARCHAR2(20 CHAR) DEFAULT 'draft' NOT NULL,
      CREATED_BY  NUMBER,
      TEMPLATE_ID VARCHAR2(100 CHAR),
      PAYLOAD     CLOB,
      CREATED_AT  TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT  TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_WEEKLY_REPORTS PRIMARY KEY (REPORT_ID),
      CONSTRAINT FK_WR_USER        FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID),
      CONSTRAINT FK_WR_TEAM        FOREIGN KEY (TEAM_ID)    REFERENCES DEPARTMENTS(DEPT_ID),
      CONSTRAINT UK_WR_TEAM_WEEK   UNIQUE (TEAM_ID, WEEK_START)
    )
  `,
  `CREATE INDEX IDX_WR_WEEK ON WEEKLY_REPORTS (WEEK_START, TEAM_ID)`,
  `
    CREATE TABLE WEEKLY_REPORT_ITEMS (
      ITEM_ID          NUMBER            GENERATED BY DEFAULT ON NULL AS IDENTITY,
      REPORT_ID        NUMBER            NOT NULL,
      ENGINEER_USER_ID NUMBER            NOT NULL,
      ITEM_TYPE        VARCHAR2(20 CHAR),
      EVENT_ID         NUMBER,
      HISTORY_ID       VARCHAR2(40 CHAR),
      PAYLOAD          CLOB,
      CONSTRAINT PK_WRI        PRIMARY KEY (ITEM_ID),
      CONSTRAINT FK_WRI_REPORT FOREIGN KEY (REPORT_ID)        REFERENCES WEEKLY_REPORTS(REPORT_ID)    ON DELETE CASCADE,
      CONSTRAINT FK_WRI_USER   FOREIGN KEY (ENGINEER_USER_ID) REFERENCES USERS(USER_ID),
      CONSTRAINT FK_WRI_HIST   FOREIGN KEY (HISTORY_ID)       REFERENCES SUPPORT_HISTORIES(HISTORY_ID),
      CONSTRAINT FK_WRI_EVENT  FOREIGN KEY (EVENT_ID)         REFERENCES EVENTS(EVENT_ID)
    )
  `,
  `CREATE INDEX IDX_WRI_REPORT ON WEEKLY_REPORT_ITEMS (REPORT_ID, ENGINEER_USER_ID)`,
];

export async function ensureWeeklyReportSchema(connection) {
  for (const ddl of DDL) {
    try { await connection.execute(ddl); }
    catch (err) { if (!isAlreadyExists(err)) throw err; }
  }
}
