SELECT
  d.DEPT_ID AS "id",
  d.DEPT_NAME AS "name",
  d.PARENT_DEPT_ID AS "parentId",
  d.SORT_ORDER AS "sortOrder",
  d.ENABLED AS "enabled",
  NVL(u.MEMBER_COUNT, 0) AS "memberCount"
FROM DEPARTMENTS d
LEFT JOIN (
  SELECT DEPT_ID, COUNT(*) AS MEMBER_COUNT
  FROM USERS WHERE ENABLED = 1 GROUP BY DEPT_ID
) u ON u.DEPT_ID = d.DEPT_ID
WHERE (:enabled_only = 0 OR d.ENABLED = 1)
ORDER BY
  CASE WHEN d.PARENT_DEPT_ID IS NULL THEN 0 ELSE 1 END,
  d.SORT_ORDER, d.DEPT_NAME
