SELECT
  shp.USER_ID AS "id",
  u.DISPLAY_NAME AS "name",
  shp.IS_MANAGER AS "isManager"
FROM SUPPORT_HISTORY_PARTICIPANTS shp
JOIN USERS u ON u.USER_ID = shp.USER_ID
WHERE shp.HISTORY_ID = :hid
ORDER BY shp.IS_MANAGER DESC, u.DISPLAY_NAME
