/**
 * 파일: backend/src/modules/audit/schema/auditSchema.ts
 * 역할: 감사 로그(AUDIT_LOGS) 테이블 DDL.
 *       관리자 작업(생성/수정/삭제)을 기록한다.
 *
 * 연관 파일:
 *   - repository/auditRepository.ts : logAudit, listAuditLogs
 *   - routes/auditRoutes.ts         : HTTP 라우트
 *   - server.ts                     : 스키마 초기화 호출
 */

import { isAlreadyExists } from '../../../infra/oracle/errorCodes.js';

const DDL: string[] = [
  `CREATE TABLE AUDIT_LOGS (
     LOG_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     ACTION      VARCHAR2(50 CHAR)   NOT NULL,
     ENTITY_TYPE VARCHAR2(100 CHAR)  NOT NULL,
     ENTITY_ID   VARCHAR2(200 CHAR),
     USER_ID     NUMBER,
     SUMMARY     VARCHAR2(500 CHAR),
     DETAIL      CLOB,
     IP_ADDR     VARCHAR2(50 CHAR),
     CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
     CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (LOG_ID)
   )`,
  `CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOGS (ENTITY_TYPE, CREATED_AT DESC)`,
  `CREATE INDEX IDX_AUDIT_USER   ON AUDIT_LOGS (USER_ID, CREATED_AT DESC)`,
];

export async function ensureAuditSchema(connection: any): Promise<void> {
  for (const ddl of DDL) {
    try { await connection.execute(ddl); }
    catch (err: any) { if (!isAlreadyExists(err)) throw err; }
  }
}
