SELECT a.ASSIGNMENT_ID AS "assignmentId", a.USER_ID AS "userId", a.ROLE AS "role",
       u.DISPLAY_NAME AS "userName", u.POSITION_NAME AS "positionName"
FROM CUSTOMER_ASSIGNMENTS a
JOIN USERS u ON u.USER_ID = a.USER_ID
WHERE a.CUSTOMER_ID = :id AND a.ENABLED = 1
ORDER BY a.ROLE, a.ASSIGNMENT_ID
