/**
 * 파일: backend/src/modules/settings/checklists/schema/checklistSchema.js
 * 역할: CHECKLIST_TEMPLATES 테이블 DDL.
 *       업무별 점검 항목 템플릿. SECTIONS_JSON에 섹션+항목 전체를 JSON으로 저장.
 *
 * 연관 파일:
 *   - backend/src/server.js : 스키마 초기화
 */

import { isAlreadyExists } from '../../../../infra/oracle/errorCodes.js';

const DDL = [
  `
    CREATE TABLE CHECKLIST_TEMPLATES (
      TEMPLATE_ID       NUMBER             GENERATED BY DEFAULT ON NULL AS IDENTITY,
      NAME              VARCHAR2(200 CHAR) NOT NULL,
      KIND              VARCHAR2(20 CHAR)  DEFAULT 'routine' NOT NULL,
      SCOPE             VARCHAR2(30 CHAR)  DEFAULT 'global'  NOT NULL,
      STATUS            VARCHAR2(20 CHAR)  DEFAULT 'draft'   NOT NULL,
      CUSTOMER_ID       NUMBER,
      SERVICE_MASTER_ID VARCHAR2(100 CHAR),
      VERSION           VARCHAR2(20 CHAR)  DEFAULT 'v1.0',
      OWNER_ID          NUMBER,
      SECTIONS_JSON     CLOB,
      ENABLED           NUMBER(1)          DEFAULT 1 NOT NULL,
      USED_BY           NUMBER             DEFAULT 0,
      CREATED_AT        TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT        TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_CHECKLIST_TEMPLATES PRIMARY KEY (TEMPLATE_ID),
      CONSTRAINT FK_CT_CUSTOMER FOREIGN KEY (CUSTOMER_ID)  REFERENCES CUSTOMERS(CUSTOMER_ID),
      CONSTRAINT FK_CT_USER     FOREIGN KEY (OWNER_ID)     REFERENCES USERS(USER_ID)
    )
  `,
  `CREATE INDEX IDX_CT_STATUS ON CHECKLIST_TEMPLATES (STATUS, KIND, SCOPE)`,
];

export async function ensureChecklistSchema(connection) {
  for (const ddl of DDL) {
    try { await connection.execute(ddl); }
    catch (err) { if (!isAlreadyExists(err)) throw err; }
  }
}
