/**
 * 파일: backend/src/modules/weekly-report/services/reportHtmlTemplates.js
 * 역할: 주간업무보고 PDF 기본 HTML/CSS 템플릿 상수.
 *       REPORT_MASTER_TEMPLATES 테이블에 템플릿이 없을 때 fallback으로 사용.
 *
 * 연관 파일:
 *   - modules/weekly-report/services/reportRenderer.js : DEFAULT_* 상수를 import
 *   - modules/settings/report-templates/repository/reportTemplateRepository.js : DB 템플릿
 */

export const DEFAULT_MASTER_REPORT_HTML = [
  '<main class="report-doc">',
  '  <header class="report-hero">',
  '    <div class="report-kicker">DATABANK SYSTEMS · IT-SCO SERVICE REPORT</div>',
  '    <div class="report-title-row">',
  '      <h1>{{title}}</h1>',
  '      <span class="report-status">{{meta.status}}</span>',
  '    </div>',
  '    <p class="report-subtitle">{{meta.customer}} · {{meta.service}} · {{meta.period}}</p>',
  '    <dl class="report-doc-info">',
  '      <div><dt>문서번호</dt><dd>{{documentNo}}</dd></div>',
  '      <div><dt>작성일시</dt><dd>{{generatedAt}}</dd></div>',
  '      <div><dt>템플릿</dt><dd>{{templateName}} {{templateVersion}}</dd></div>',
  '    </dl>',
  '  </header>',
  '  <section class="report-control-band">',
  '    <div><span>Customer</span><b>{{meta.customer}}</b></div>',
  '    <div><span>Service</span><b>{{meta.service}}</b></div>',
  '    <div><span>Owner</span><b>{{meta.owner}}</b></div>',
  '    <div><span>Method</span><b>{{meta.method}}</b></div>',
  '  </section>',
  '  <section class="report-meta">{{metaRows}}</section>',
  '  <section class="report-section report-summary-section">',
  '    <div class="report-section-head">',
  '      <span>01</span>',
  '      <div><h2>운영 요약 지표</h2><p>자동 산출된 상태/성능 지표를 기준으로 점검 결과를 빠르게 확인합니다.</p></div>',
  '    </div>',
  '    <div class="report-chart-frame">{{chartsHtml}}</div>',
  '  </section>',
  '  <section class="report-section report-body-section">',
  '    <div class="report-section-head">',
  '      <span>02</span>',
  '      <div><h2>고객 공유 본문</h2><p>엔지니어 검토 후 고객에게 전달되는 핵심 내역입니다.</p></div>',
  '    </div>',
  '    <div class="report-body">{{bodyHtml}}</div>',
  '  </section>',
  '  <section class="report-review-note">',
  '    <b>검토 기준</b>',
  '    <span>본문의 수치, 조치 결과, 후속 일정은 원천 이력과 대조 후 확정합니다.</span>',
  '  </section>',
  '  {{signatureBlock}}',
  '  <footer class="report-footer"><span>{{templateName}} {{templateVersion}}</span><span>DATABANK SYSTEMS · CONFIDENTIAL · {{generatedAt}}</span></footer>',
  '</main>',
].join('\n');

export const DEFAULT_MASTER_REPORT_CSS = [
  '@page { size: A4; margin: 13mm 12mm 14mm; }',
  '* { box-sizing: border-box; }',
  'body { margin: 0; font-family: "Malgun Gothic", "맑은 고딕", Arial, sans-serif; color: #172033; font-size: 11.5px; line-height: 1.62; background: #ffffff; }',
  '.report-doc { position: relative; width: 100%; min-height: 100%; padding-top: 2px; }',
  '.report-doc::before { content: ""; display: block; height: 5px; margin-bottom: 18px; border-radius: 999px; background: linear-gradient(90deg, #0f2a44 0%, #176b87 48%, #4fb3a3 100%); }',
  '.report-hero { display: grid; grid-template-columns: minmax(0, 1fr) 240px; gap: 22px; align-items: start; padding-bottom: 18px; border-bottom: 1px solid #cfd7e3; margin-bottom: 14px; }',
  '.report-kicker { grid-column: 1 / -1; color: #176b87; font-size: 10px; font-weight: 900; letter-spacing: .16em; text-transform: uppercase; }',
  '.report-title-row { min-width: 0; display: flex; align-items: flex-start; gap: 12px; }',
  'h1 { flex: 1; margin: 0; color: #0f172a; font-size: 26px; line-height: 1.22; letter-spacing: -.02em; font-weight: 900; word-break: keep-all; }',
  '.report-status { display: inline-flex; align-items: center; min-height: 24px; padding: 4px 11px; border-radius: 999px; background: #e9f8f5; color: #0f766e; border: 1px solid #b7e4dc; font-size: 11px; font-weight: 900; white-space: nowrap; }',
  '.report-subtitle { margin: 8px 0 0; color: #64748b; font-weight: 700; }',
  '.report-doc-info { margin: 0; display: grid; gap: 6px; color: #475569; font-size: 10.5px; }',
  '.report-doc-info div { display: grid; grid-template-columns: 66px minmax(0, 1fr); gap: 10px; align-items: baseline; }',
  '.report-doc-info dt { color: #0f172a; font-weight: 900; }',
  '.report-doc-info dd { margin: 0; text-align: right; overflow-wrap: anywhere; }',
  '.report-control-band { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px; margin-bottom: 14px; }',
  '.report-control-band div { min-height: 58px; padding: 10px 12px; border-radius: 12px; background: #f7fafc; border: 1px solid #dbe4ee; }',
  '.report-control-band span { display: block; margin-bottom: 3px; color: #64748b; font-size: 9.5px; font-weight: 900; letter-spacing: .08em; text-transform: uppercase; }',
  '.report-control-band b { display: block; color: #0f172a; font-size: 12px; line-height: 1.35; overflow-wrap: anywhere; }',
  '.report-meta { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); border: 1px solid #cfd7e3; border-radius: 12px; overflow: hidden; margin-bottom: 18px; }',
  '.report-meta-cell { min-height: 50px; padding: 9px 11px; border-right: 1px solid #d8e0ea; border-bottom: 1px solid #d8e0ea; background: #fff; }',
  '.report-meta-cell:nth-child(4n) { border-right: 0; }',
  '.report-meta-cell:nth-last-child(-n + 4) { border-bottom: 0; }',
  '.report-meta-cell span { display: block; margin-bottom: 4px; font-size: 9.5px; font-weight: 900; color: #64748b; text-transform: uppercase; letter-spacing: .06em; }',
  '.report-meta-cell b { display: block; font-size: 12px; color: #0f172a; line-height: 1.35; overflow-wrap: anywhere; }',
  '.report-section { margin-bottom: 19px; page-break-inside: avoid; }',
  '.report-section-head { display: grid; grid-template-columns: 36px minmax(0, 1fr); gap: 10px; align-items: start; margin-bottom: 10px; }',
  '.report-section-head > span { width: 30px; height: 30px; display: inline-flex; align-items: center; justify-content: center; border-radius: 10px; background: #0f2a44; color: #ffffff; font-size: 11px; font-weight: 900; }',
  'h2 { margin: 0; color: #111827; font-size: 15px; line-height: 1.25; font-weight: 900; }',
  '.report-section-head p { margin: 3px 0 0; color: #64748b; font-size: 10.5px; }',
  '.report-chart-frame { padding: 12px; border: 1px solid #d8e0ea; border-radius: 14px; background: linear-gradient(180deg, #f8fbfd 0%, #ffffff 100%); }',
  '.report-body { min-height: 245px; padding: 18px 20px; border: 1px solid #cfd7e3; border-radius: 14px; background: #ffffff; color: #1f2937; word-break: keep-all; box-shadow: inset 4px 0 0 #176b87; }',
  '.report-review-note { display: grid; grid-template-columns: 86px minmax(0, 1fr); gap: 12px; align-items: start; padding: 12px 14px; border: 1px solid #d8e0ea; border-radius: 12px; background: #f8fafc; color: #475569; margin: 6px 0 18px; page-break-inside: avoid; }',
  '.report-signature { margin-top: 20px; page-break-inside: avoid; }',
  '.report-signature h2 { margin: 0 0 10px; padding-bottom: 7px; border-bottom: 1px solid #cfd7e3; }',
  '.report-signature-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }',
  '.report-signature-box { min-height: 118px; padding: 12px 14px; border: 1px solid #b8c4d3; border-radius: 12px; background: #fff; }',
  '.report-signature-box span { display: block; color: #64748b; font-size: 10px; font-weight: 900; letter-spacing: .05em; }',
  '.report-signature-box b { display: block; margin-top: 4px; color: #0f172a; font-size: 13px; }',
  '.report-signature-line { height: 44px; margin: 10px 0 7px; border-bottom: 1px solid #94a3b8; }',
  '.report-footer { margin-top: 22px; padding-top: 10px; border-top: 1px solid #cfd7e3; display: flex; justify-content: space-between; gap: 12px; color: #94a3b8; font-size: 9.5px; font-weight: 800; letter-spacing: .04em; }',
].join('\n');
