/**
 * 파일: backend/src/modules/settings/ai-models/schema/aiModelSchema.js
 * 역할: AI_MODELS 테이블 DDL. AI 모델 설정(공급자, 엔드포인트, API 키, 사용량).
 *       USE_CASES는 콤마 구분 문자열로 저장.
 *
 * 연관 파일:
 *   - repository/aiModelRepository.js
 *   - backend/src/server.js : 스키마 초기화
 */

import { isAlreadyExists } from '../../../../infra/oracle/errorCodes.js';

const DDL = [
  `
    CREATE TABLE AI_MODELS (
      MODEL_ID      NUMBER             GENERATED BY DEFAULT ON NULL AS IDENTITY,
      NAME          VARCHAR2(100 CHAR) NOT NULL,
      VERSION       VARCHAR2(50 CHAR),
      PROVIDER      VARCHAR2(50 CHAR)  DEFAULT 'anthropic',
      STATUS        VARCHAR2(20 CHAR)  DEFAULT 'active' NOT NULL,
      ENDPOINT      VARCHAR2(500 CHAR),
      API_KEY       VARCHAR2(500 CHAR),
      TOKENS_USED   NUMBER             DEFAULT 0,
      TOKEN_LIMIT      NUMBER             DEFAULT 1000000,
      COST_MONTH       NUMBER             DEFAULT 0,
      CONTEXT_LIMIT_KB NUMBER             DEFAULT 0,
      IS_TRAINING      NUMBER(1)          DEFAULT 0,
      IS_DEFAULT    NUMBER(1)          DEFAULT 0,
      NOTES         VARCHAR2(2000 CHAR),
      USE_CASES     VARCHAR2(500 CHAR),
      CREATED_AT    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
      THINKING_MODE   VARCHAR2(10 CHAR) DEFAULT 'auto',
      THINKING_FAMILY VARCHAR2(20 CHAR) DEFAULT 'none',
      CONSTRAINT PK_AI_MODELS PRIMARY KEY (MODEL_ID),
      CONSTRAINT CHK_AI_STATUS CHECK (STATUS IN ('active','beta','inactive'))
    )
  `,
];

const MIGRATION_DDL = [
  `ALTER TABLE AI_MODELS ADD CONTEXT_LIMIT_KB NUMBER DEFAULT 0`,
  `ALTER TABLE AI_MODELS ADD MODEL_TYPE VARCHAR2(20 CHAR) DEFAULT 'llm'`,
  `ALTER TABLE AI_MODELS ADD THINKING_MODE   VARCHAR2(10 CHAR) DEFAULT 'auto'`,
  `ALTER TABLE AI_MODELS ADD THINKING_FAMILY VARCHAR2(20 CHAR) DEFAULT 'none'`,
];

export async function ensureAiModelSchema(connection) {
  for (const ddl of MIGRATION_DDL) {
    try { await connection.execute(ddl); } catch (_) {}
  }
  for (const ddl of DDL) {
    try { await connection.execute(ddl); }
    catch (err) { if (!isAlreadyExists(err)) throw err; }
  }
}
