/**
 * 파일: backend/src/modules/matrix/schema/matrixSchema.js
 * 역할: 작업현황표 테이블 DDL.
 *       ROUTINE_PLANS(고객×서비스×반기 계획), ROUTINE_PLAN_CELLS(월별 상태).
 *       CUSTOMERS FK + SUPPORT_HISTORIES HISTORY_ID FK 포함.
 *
 * 연관 파일:
 *   - repository/matrixRepository.js
 *   - backend/src/server.js : 스키마 초기화 (ensureSupportHistorySchema 뒤에 호출)
 */

import { isAlreadyExists } from '../../../infra/oracle/errorCodes.js';

const DDL = [
  `
    CREATE TABLE ROUTINE_PLANS (
      PLAN_ID      NUMBER            GENERATED BY DEFAULT ON NULL AS IDENTITY,
      CUSTOMER_ID  NUMBER            NOT NULL,
      SERVICE_NAME VARCHAR2(200 CHAR) NOT NULL,
      PERIOD_YEAR  NUMBER            NOT NULL,
      PERIOD_HALF  NUMBER(1)         NOT NULL,
      TARGET_FREQ  VARCHAR2(40 CHAR),
      ENABLED      NUMBER(1)         DEFAULT 1 NOT NULL,
      CREATED_AT   TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_ROUTINE_PLANS PRIMARY KEY (PLAN_ID),
      CONSTRAINT FK_RP_CUSTOMER   FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
      CONSTRAINT UK_RP_UNIT       UNIQUE (CUSTOMER_ID, SERVICE_NAME, PERIOD_YEAR, PERIOD_HALF),
      CONSTRAINT CHK_RP_HALF      CHECK (PERIOD_HALF IN (1, 2))
    )
  `,
  `CREATE INDEX IDX_RP_YEAR_HALF ON ROUTINE_PLANS (PERIOD_YEAR, PERIOD_HALF, ENABLED)`,
  `CREATE INDEX IDX_RP_CUSTOMER  ON ROUTINE_PLANS (CUSTOMER_ID)`,
  `
    CREATE TABLE ROUTINE_PLAN_CELLS (
      PLAN_ID      NUMBER            NOT NULL,
      PERIOD_MONTH NUMBER(2)         NOT NULL,
      STATUS       VARCHAR2(20 CHAR) DEFAULT 'pending' NOT NULL,
      HISTORY_ID   VARCHAR2(40 CHAR),
      UPDATED_AT   TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_RPC          PRIMARY KEY (PLAN_ID, PERIOD_MONTH),
      CONSTRAINT FK_RPC_PLAN     FOREIGN KEY (PLAN_ID)    REFERENCES ROUTINE_PLANS(PLAN_ID)    ON DELETE CASCADE,
      CONSTRAINT FK_RPC_HISTORY  FOREIGN KEY (HISTORY_ID) REFERENCES SUPPORT_HISTORIES(HISTORY_ID),
      CONSTRAINT CHK_RPC_MONTH   CHECK (PERIOD_MONTH BETWEEN 1 AND 12)
    )
  `,
];

export async function ensureMatrixSchema(connection) {
  for (const ddl of DDL) {
    try { await connection.execute(ddl); }
    catch (err) { if (!isAlreadyExists(err)) throw err; }
  }
}
